# This is a basic workflow to help you get started with Actions
name: moxunit_master_test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-with-coverage:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run unit tests
      uses: joergbrech/moxunit-action@master
      with:
        src: tests/src,tests/srcB
        with_coverage: true
  test-cover-xml-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run unit tests
      uses: joergbrech/moxunit-action@master
      with:
        src: tests/src tests/srcB
        cover_xml_file: coverage.xml
    - uses: actions/upload-artifact@v1
      with:
        name: coverage_file
        path: coverage.xml
    - uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
  tests2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: joergbrech/moxunit-action@master
        with:
          tests: ./testFolder/mySimpleTest2.m
